### ISSUE TITLE
Wordpress 4.3 update 

### ISSUE THREAD

**Issue by salignou** [meta4creations/ditty-news-ticker#1]
Hello, 
I love your wordpress plugin, could you please update it so that it function again with 4.3 ? 
https://make.wordpress.org/core/2015/07/02/deprecating-php4-style-constructors-in-wordpress-4-3/
Thank you very much !!
Sarah

**Comment by meta4creations** [comment]
Sarah, the plugin is tested and working with WP 4.3. If you are having issues with it working on your site it could be due to a javascript error within another plugin or theme that was updated.

## 

Joe Anderson
Sent with Sparrow (http://www.sparrowmailapp.com/?sig)

**Comment by salignou** [comment]
Hey,
Thanks you for you quick reply. I'm not sure it's javascript error : :

The called constructor method for WP_Widget is deprecated since version
4.3.0! Use

__construct()

instead. in /home/metranspcm/www/news/wp-includes/functions.php on line 3457

Warning: The URL
http://www.metaphorcreations.com/envato/plugins/ditty-rss-ticker/auto-update.json?checking_for_updates=1&installed_version=1.0.10
does not point to a valid plugin metadata file. HTTP response code is 403
(expected: 200) in
/home/metranspcm/www/news/wp-content/plugins/ditty-rss-ticker/includes/plugin-updates/plugin-update-checker.php
on
line 190

Could you check again ?

Thank you !!
Sarah
ᐧ

Sarah AKEL
akel.sarah@gmail.com
06 69 56 50 97

www.rhmooc.com

2015-08-20 2:04 GMT+02:00 Joe Anderson notifications@github.com:

**Comment by meta4creations** [comment]
Ok, I see this now. I have updated the plugin to resolve this issue. Thanks for letting me know!
