### ISSUE TITLE
Error /includes/class-ditty-translations.php:217

### ISSUE THREAD

**Issue by Neuzeitprophet** [meta4creations/ditty-news-ticker#3]
﻿﻿I have problems with 3.1.26 and the current wordpress version. Some subpages no longer load when the plugin is active. I get the following error: 

mod_fcgid: stderr: PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function Ditty_Translations::translate_title(), 1 passed in /var/www/vhosts/website/httpdocs/wp-includes/class-wp-hook.php on line 310 and exactly 2 expected in /var/www/vhosts/website/httpdocs/wp-content/plugins/ditty-news-ticker/includes/class-ditty-translations.php:217

**Comment by meta4creations** [comment]
Thanks for letting me know. I'll release an update today that should resolve this issue.

**Comment by meta4creations** [comment]
I just released an update that should resolve this. (3.1.27). Let me know if you run into anything else.

**Comment by Neuzeitprophet** [comment]
thank you very much. it's running :)
